### ISSUE TITLE
Programmatically launch the authenticator

### ISSUE THREAD

**Issue by vinodc** [Kloudless/authenticator.js#1]
It would be great if we could programmatically launch the authenticator when needed rather than binding it to a DOM element.

**Comment by moltar** [comment]
You could still do it by binding to an empty element, and then triggering a click event. I know it's a hack, and would be great to have a proper solution. Just saying if you are in a crunch, it's possible.

**Comment by vinodc** [comment]
@moltar Thanks for the insight. Looks like the https://github.com/Kloudless/authenticator.js#objlaunch method helps now.
