### ISSUE TITLE
Prevent unnecessary "Origin mismatch" log messages

### ISSUE THREAD

**Issue by vinodc** [Kloudless/authenticator.js#5]
If a posted message's origin does not match what the Kloudless code expects to receive, the Authenticator should simply ignore the message rather than log the failure. The logging is unnecessary and spams the console if any other JS on that page is using cross-origin communication.

While useful for debugging purposes, it should be possible to toggle via the configuration rather than indiscriminately logged.

**Comment by mandemeskel** [comment]
To add to that, I noticed this excessive logging can also cause Safari to stop working and even crash. A fix would be much appreciated!

**Comment by hong19** [comment]
@mandemeskel  It's fixed at af1930070ae0ef7dceebd1644599ebe84986cf27
